FROM python:3.12.3

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && apt-get install -y netcat httpie; \
    pip install --upgrade pip && pip install flask

RUN mkdir /code
WORKDIR /code
COPY ./server.py .

ENTRYPOINT ["python", "./server.py"]